enmc/enmc/apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from apps.users.views import UserListView, UserDetailView, UserDeleteView, LoginView, ResetPwdView, user_logout

app_name = '[users]'
urlpatterns = [
    url(r'^$', UserListView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^reset_pwd/$', ResetPwdView.as_view(), name='reset_pwd'),

    # 用户管理
    url(r'^user_detail/$', UserDetailView.as_view(), name='user_detail'),
    url(r'^user_delete/$', UserDeleteView.as_view(), name='user_delete'),
]

enmc/enmc/enmc/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve


from apps.equipments.views import index
from enmc.settings import MEDIA_ROOT
import xadmin


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    url(r'^(?:index.html)?$', index, name='index'),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^directories/', include('apps.directories.urls', namespace='directories')),
    url(r'^equipments/', include('apps.equipments.urls', namespace='equipments')),
    url(r'^applications/', include('apps.applications.urls', namespace='applications')),
    url(r'^search/', include('apps.search.urls', namespace='search')),

    # 配置上传文件的访问处理
    url(r'^upload/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

enmc/enmc/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>网管系统</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}

    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}

    {% endblock %}

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <!--已经登录的状态-->
                    <div class="personal">
                        <dl class="user fr">
                            <dd>{{ request.user.username }}<img class="down fr"
                                                                src="{% static 'images/top_down.png' %}"/>
                            </dd>
                            <dt><img width="20" height="20"
                                     src="{{ MEDIA_URL }}{{ request.user.avatar }}"/>
                            </dt>
                        </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80"
                                         src="{{ MEDIA_URL }}{{ request.user.avatar }}"/></dt>
                                <dd>
                                    <p align="left">邮箱地址：{{ request.user.email }}</p>
                                    <p align="left">手机号码：{{ request.user.mobile }}</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="{% url 'users:reset_pwd' %}">修改密码</a>
                                <a class="fr" href="{% url 'users:logout' %}">退出</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="/static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="ip">
                                IP搜索
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="ip">IP搜索</li>
                                <li data-value="domain">域名搜索</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>
            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li {% block menu_index %}

                            {% endblock %}><a href="{% url 'index' %}">首页</a></li>
                            <li {% block menu_equipments %}

                            {% endblock %}><a href="{% url '[equipments]:index' %}">设备管理</a></li>
                            <li {% block menu_applications %}

                            {% endblock %}><a href="{% url '[applications]:index' %}">应用管理</a></li>

                            {% if request.user.is_superuser %}
                                <li {% block menu_users %}

                                {% endblock %}><a href="{% url '[users]:index' %}">用户管理</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
</section>
<!--crumbs start-->
{#{% block custom_bread %}#}
{#    <section>#}
{#        <div class="wp">#}
{#            <ul class="crumbs">#}
{#                <li><a href="{% url 'index' %}">首页</a>></li>#}
{#            </ul>#}
{#        </div>#}
{#    </section>#}
{#{% endblock %}#}

{% block content %}

{% endblock %}

{#<footer>#}
{#		<div class="footer">#}
{#			<p class="line"></p>#}
{#			<div class="wp clear">#}
{#                <span class="fl">禁止使用 - 违者必究 - 如不使用 - 来者为何 - 来看看 - 看看 - 看</span>#}
{#                <span class="fr">ICP备案证书号：国ICP备66666666号-1</span>#}
{#			</div>#}
{#		</div>#}
{#</footer>#}

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/index.js' %}" type="text/javascript"></script>

</body>
</html>

enmc/enmc/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block menu_index %}
class="active"
{% endblock %}

{% block custom_css %}
    <style type="text/css">
    .main{
        position:absolute;
        top:50%;
        left:50%;
        width:400px;
        height:500px;
        margin-top:-250px;
        margin-left:-200px;
        {#border:1px solid red;#}
        line-height:30px;
        font-size:16px;
        text-align:center;
        background-color:#E3E3E3;
        }
    </style>
{% endblock %}

{% block content %}
    <section>
        <div class="wp butler_list_box list">
            <div class='left'>
                {% for country in countrys %}
                <div class="layout" style="margin:15px; margin-top: 50px; border:0;padding:0;">
                <form id="{{ country.countryid }}_form">
                {% csrf_token %}
                    <div class="head">
                        <ul class="tab_header">
                            <input type="hidden" name="countryid" id="DeleteCountryId" value="{{ country.countryid }}">
                            <li><label>地区：</label><a href="{% url '[equipments]:room_detail' %}?countryid={{ country.countryid }}" style="font-size: 20px; color: #00B23B">{{ country.name }}</a></li>
                            <li><label>查看机房：</label></li>
                            {% for room in rooms %}
                                {% if room.country_id == country.countryid %}
                                    <li><a href="{% url '[equipments]:room_detail' %}?countryid={{ country.countryid }}">{{ room.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    <textarea name="remark" id="{{ country.countryid }}_remark" rows="20" cols="90" placeholder="备注:">{% if country.remark %}{{ country.remark }}{% endif %}</textarea>
                    <input id="DetailCountryBtn" type="button" onclick="show('{{ country.countryid }}','{{ country.name }}','{{ country.countryid }}_remark')" style="width: 100px; height: 50px;"
                       value="编&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;辑"/>
                    <input id="DeleteCountryBtn" type="button" onclick="DeleteCountry('{{ country.countryid }}_form')" style="width: 100px; height: 50px;"
                       value="删&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;除"/>
                </form>
                </div>
                {% endfor %}
            </div>

            <div class="right companyright" >
                <div class="head">添加地区</div>
                <form class="rightform" id="AddCountryForm">
                    {% csrf_token %}
                    <input type="hidden" name="countryid" id="AddCountryId" value="{{ new_countryid }}">
                    <div style="margin-top: 10px; border:0;padding:0;">
                        <input type="text" style="width: 215px" name="name" id="AddCountryName" placeholder="地区名称" maxlength="30"/>
                    </div>
                    <div style="margin-top: 20px; border:0;padding:0;">
                        <textarea rows="10" cols="33" name="remark" id="AddCountryRemark" placeholder="备注:" data-value=""></textarea>
                    </div>
                    <div style="margin-top: 110px; border:0;padding:0;">
                        <input style="width: 215px; height: 40px; color: #fff; background-color: #00B23B" type="button" id="AddCountryBtn" onclick="CommitCountry('AddCountryForm')" value="提&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;交"/>
                    </div>
                </form>
            </div>
        </div>

        {# 修改地区Div #}
        <div class="main" id="main" hidden="hidden">
            <div class="head">修改地区</div>
                <form class="detailform" id="DetailCountryForm">
                    {% csrf_token %}
                    <div style="margin-top: 10px; border:0;padding:0;">
                        <label>地区名称：</label>
                        <input type="hidden" name="countryid" id="DetailCountryId" value="">
                        <input name="name" id="DetailCountryName" type="text" style="width: 215px"  maxlength="30" value=""/>
                    </div>
                    <div style="margin-top: 20px; border:0;padding:0;">
                        <textarea rows="20" cols="45" name="remark" id="DetailCountryRemark" placeholder="备注:" data-value=""></textarea>
                    </div>
                    <div style="margin-top: 10px; border:0;padding:0;">
                        <input style="width: 150px; height: 40px; color: #fff; background-color: #00B23B" type="button" id="CommitCountryBtn" onclick="CommitCountry('DetailCountryForm')" value="提&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;交"/>
                        <input style="width: 150px; height: 40px; color: #fff; background-color: #00B23B" type="button" id="CancelCountryBtn" onclick="hide()" value="取&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;消"/>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

{% block custom_js %}
    {# 显示和隐藏编辑窗口 #}
    <script type="text/javascript">
        function show(countryid, name, remark) {
            document.getElementById("DetailCountryId").value=countryid;
            document.getElementById("DetailCountryName").value=name;
            document.getElementById("DetailCountryRemark").value=document.getElementById(remark).value;

            var hy = (document.documentElement.scrollTop || document.body.scrollTop) + 260;
            document.getElementById("main").style.top = hy + 'px';
            document.getElementById("main").style.display='inline';
        }
        {# 清空内容，并隐藏 #}
        function hide() {
            document.getElementById("main").style.display='none';
        }
    </script>

    {# 添加地区 #}
    <script>
    function CommitCountry(form) {
        $.ajax({
                cache:false,
                type:'POST',
                url:"{% url '[equipments]:country_detail' %}",
                data:$('#'+form).serialize(),
                async:true,
                success: function (data) {
                    console.log(data)
                    if(data.status == 'success'){
                        alert('提交成功'),
                        window.location.href="{% url 'index' %}"
                    }else{
                        alert('提交失败')
                    }
                }
            })
    }
    </script>

    {# 删除地区 #}
    <script>
    function DeleteCountry(form) {
        $.ajax({
                cache:false,
                type:'POST',
                url:"{% url '[equipments]:country_delete' %}",
                data:$('#'+form).serialize(),
                async:true,
                success: function (data) {
                    console.log(data)
                    if(data.status == 'success'){
                        alert('提交成功'),
                        window.location.href="{% url 'index' %}"
                    }else{
                        alert(data.msg)
                    }
                }
            })
    }
    </script>
{% endblock %}

enmc/enmc/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>网管系统</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<header>
</header>
<section>
    <div class="fl form-box">
        <h2>登录网管系统</h2>
        <form action="{% url '[users]:login' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="form-group marb20 {% if login_form.errors.username  %}
                       errorput
                    {% endif %}">
                <label>用&nbsp;户&nbsp;名</label>
                <input name="username" id="account_l" type="text" placeholder="请输入用户名"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
                {{ login_form.errors.username }}
            </div>
            <div class="form-group marb8 {% if login_form.errors.password %}
                       errorput
                    {% endif %}">
                <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                <input name="password" id="password_l" type="password" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
                {{ login_form.errors.password }}
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
                {{ msg }}
            </div>
            <div class="auto-box marb38">
            </div>
            <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > "/>
        </form>
    </div>
</section>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/login.js" type="text/javascript"></script>
</body>
</html>

enmc/enmc/templates/password_reset.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>网管系统</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<header>
</header>
<section>
    <div class="fl form-box">
        <h2>修改密码</h2>
        <form action="{% url '[users]:reset_pwd' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="form-group marb20 {% if login_form.errors.password  %}
                       errorput
                    {% endif %}">
                <label>新&nbsp;密&nbsp;码</label>
                <input name="password" id="account_l" type="password" placeholder="请输入新密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
                {{ reset_pwd_form.errors.password }}
            </div>
            <div class="form-group marb8 {% if login_form.errors.password2 %}
                       errorput
                    {% endif %}">
                <label>确认密码</label>
                <input name="password2" id="password_l" type="password" placeholder="请再次输入密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
                {{ reset_pwd_form.errors.password2 }}
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
                {{ msg }}
            </div>
            <div class="auto-box marb38">
            </div>
            <input class="btn btn-green" id="xiugaimima" type="submit" value="修改密码">
        </form>
    </div>
</section>
{#<script src="/static/js/jquery.min.js" type="text/javascript"></script>#}
{#<script src="/static/js/unslider.js" type="text/javascript"></script>#}
{#<script src="/static/js/login.js" type="text/javascript"></script>#}
</body>
</html>