enmc/enmc/apps/equipments/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from apps.equipments.views import *

app_name = '[equipments]'
urlpatterns = [
    url(r'^$', ListView.as_view(), name='index'),

    # 设备管理
    url(r'^equipment_detail/$', EquipmentDetailView.as_view(), name='equipment_detail'),
    url(r'^equipment_delete/$', EquipmentDeleteView.as_view(), name='equipment_delete'),

    # 编辑服务
    url(r'^service_detail/$', ServiceDetailView.as_view(), name='service_detail'),
    url(r'^service_delete/$', ServiceDeleteView.as_view(), name='service_delete'),

    # 编辑地区
    url(r'^country_detail/$', CountryDetailView.as_view(), name='country_detail'),
    url(r'^country_delete/$', CountryDeleteView.as_view(), name='country_delete'),
    # 编辑机房
    url(r'^room_detail/$', RoomDetailView.as_view(), name='room_detail'),
    url(r'^room_delete/$', RoomDeleteView.as_view(), name='room_delete'),
    # 编辑机柜
    url(r'^cabinet_detail/$', CabinetDetailView.as_view(), name='cabinet_detail'),
    url(r'^cabinet_delete/$', CabinetDeleteView.as_view(), name='cabinet_delete'),

    # 动态获取地区、机房、机柜信息
    url(r'^equipment_getdata/$', EquipmentGetDataView.as_view(), name='equipment_getdata'),
]

enmc/enmc/enmc/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve


from apps.equipments.views import index
from enmc.settings import MEDIA_ROOT
import xadmin


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    url(r'^(?:index.html)?$', index, name='index'),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^directories/', include('apps.directories.urls', namespace='directories')),
    url(r'^equipments/', include('apps.equipments.urls', namespace='equipments')),
    url(r'^applications/', include('apps.applications.urls', namespace='applications')),
    url(r'^search/', include('apps.search.urls', namespace='search')),

    # 配置上传文件的访问处理
    url(r'^upload/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

enmc/enmc/apps/equipments/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models


class Country(models.Model):
    # 地区ID，以"g"开头，后面跟3位数字。如：g001
    countryid = models.CharField(primary_key=True, max_length=4, verbose_name=u'地区ID')
    name = models.CharField(unique=True, max_length=50, verbose_name=u'国家地区')
    remark = models.TextField(null=True, blank=True, verbose_name=u'备注')

    class Meta:
        verbose_name = u'国家地区表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Room(models.Model):
    # 机房ID，以"地区ID"开头，再连接"r"开头，后面跟3位数字。如：g001r001
    roomid = models.CharField(primary_key=True, max_length=8, verbose_name=u'机房ID')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name=u'地区ID')
    name = models.CharField(unique=True, max_length=100, null=False, blank=False, verbose_name=u'机房名称')
    roomaddress = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'机房地址')
    isp = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'托管商')
    remark = models.TextField(null=True, blank=True, verbose_name=u'备注')

    class Meta:
        verbose_name = u'机房信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Cabinet(models.Model):
    # 机柜ID，以"地区ID机房ID"开头，再连接"j"开头，后面跟3位数字。如：g001r001j001
    cabinetid = models.CharField(primary_key=True, max_length=12, verbose_name=u'机柜ID')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name=u'地区ID')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name=u'机房ID')
    name = models.CharField(unique=True, max_length=10, verbose_name=u'机柜名称')
    network = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'网络线路')
    start_time = models.DateTimeField(null=True, blank=True, verbose_name=u'合约开始时间')
    stop_time = models.DateTimeField(null=True, blank=True, verbose_name=u'合约结束时间')
    remark = models.TextField(null=True, blank=True, verbose_name=u'备注')

    class Meta:
        verbose_name = u'机柜信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class EquipmentType(models.Model):
    equipment_typeid = models.CharField(primary_key=True, max_length=3, verbose_name=u'类型ID')
    name = models.CharField(unique=True, max_length=20, verbose_name=u'类型名称')

    class Meta:
        verbose_name = u'设备类型表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Status(models.Model):
    status = models.CharField(max_length=8, choices=(('zaiyong', u'在用'), ('kongxian', u'空闲'), ('weixiu', u'维修')),
                              default='kongxian', verbose_name=u'设备状态')

    class Meta:
        verbose_name = u'状态表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.status


class Equipment(models.Model):
    # 主键
    # 设备ID，以"地区ID机房ID机柜ID"开头，再连接"e"开头，后面跟5位数字。如：g001r001j001e00001
    equipmentid = models.CharField(primary_key=True, max_length=18, verbose_name=u'设备ID')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name=u'地区ID')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name=u'机房ID')
    cabinet = models.ForeignKey(Cabinet, on_delete=models.CASCADE, verbose_name=u'机柜ID')
    status = models.ForeignKey(Status, on_delete=models.CASCADE, verbose_name=u'设备状态')
    relatedid = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'交换机设备关联ID')
    relatedport = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'关联交换机端口')
    # 设备类型，对应设备类型表
    equipment_type = models.ForeignKey(EquipmentType, on_delete=models.CASCADE, verbose_name=u'设备类型')
    mother = models.GenericIPAddressField(max_length=18, null=True, blank=True, verbose_name=u'宿主ID')
    sn = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'设备SN码')
    hostname = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'主机名')
    system = models.CharField(max_length=30, null=True, blank=True, verbose_name=u'操作系统')
    cpu = models.CharField(max_length=6, null=True, blank=True, verbose_name=u'CPU核数')
    memory = models.CharField(max_length=10, null=True, blank=True, verbose_name=u'内存大小')
    disk = models.CharField(max_length=10, null=True, blank=True, verbose_name=u'磁盘大小')
    ssh_port = models.CharField(null=True, blank=True, max_length=5, verbose_name=u'SSH端口')
    ip = models.GenericIPAddressField(unique=True, verbose_name=u'Ip地址')
    ip1 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址1')
    ip2 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址2')
    ip3 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址3')
    ip4 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址4')
    ip5 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址5')
    ip6 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址6')
    ip7 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址7')
    ip8 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址8')
    ip9 = models.GenericIPAddressField(null=True, blank=True, verbose_name=u'Ip地址9')
    addtime = models.DateTimeField(default=datetime.now, verbose_name=u'创建时间')
    updatetime = models.DateTimeField(default=datetime.now, verbose_name=u'更新时间')
    remark = models.TextField(null=True, blank=True, verbose_name=u'备注')

    class Meta:
        verbose_name = u'设备信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ip

class Service(models.Model):
    # 服务ID，以"s"开头，后面跟3位数字。如：s001
    serviceid = models.CharField(primary_key=True, max_length=4, verbose_name=u'服务ID')
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, verbose_name=u'设备ID')
    name = models.CharField(max_length=20, verbose_name=u'服务名称')
    install = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'安装路径')
    config = models.CharField(max_length=200, null=True, blank=True, verbose_name=u'配置文件')
    start = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'启动文件')
    version = models.CharField(max_length=50, null=True, blank=True, verbose_name=u'软件版本')
    port = models.CharField(max_length=5, null=True, blank=True, verbose_name=u'端口号')
    protocol = models.CharField(max_length=3, null=True, blank=True, choices=(('tcp', u'TCP'), ('udp', u'UDP')),
                            default='tcp', verbose_name=u'协议类型')
    user = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'用户名')
    password = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'密码')
    remark = models.TextField(null=True, blank=True,verbose_name=u'备注')

    class Meta:
        verbose_name = u'服务信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

enmc/enmc/apps/equipments/forms.py
# -*- coding: utf-8 -*-
from django import forms

from apps.search.views import SearchEquipment
from apps.equipments.models import Country, Room, Cabinet, Equipment


class ServiceDetailForms(forms.ModelForm):

    class Meta:
        fields = ['name']


class EquipmentDetailForms(forms.ModelForm):
    def clean_ip(self):
        equipment_type = self.cleaned_data.get('equipment_type')
        mother = self.cleaned_data.get('mother')
        ip = self.cleaned_data.get('ip')
        cabinet = self.cleaned_data.get('cabinet').pk

        if equipment_type.name == 'VM' and mother != '':
            equipment = SearchEquipment.ip(mother)
            if equipment.equipment_type_id != '3':
                raise forms.ValidationError(mother + '不存在或者不是ALONE')
            if equipment.cabinet_id != cabinet:
                raise forms.ValidationError(mother + '与' + ip + '不再同一个机柜')

        if mother == '' and equipment_type.name == 'VM':
            raise forms.ValidationError('你选择的设备类型为VM，请填写宿主机IP地址。')

        if mother != '' and equipment_type.name != 'VM':
            raise forms.ValidationError('请设置设备类型为VM。')

        return ip

    class Meta:
        model = Equipment
        fields = '__all__'
        exclude = ['addtime', 'updatetime']


class CountryDetailForms(forms.ModelForm):

    class Meta:
        model = Country
        fields = '__all__'


class RoomDetailForms(forms.ModelForm):

    class Meta:
        model = Room
        fields = '__all__'


class CabinetDetailForms(forms.ModelForm):

    class Meta:
        model = Cabinet
        fields = '__all__'

enmc/enmc/apps/equipments/templates/equipments_base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_bread %}

{% endblock %}

{% block menu_equipments %}
class="active"
{% endblock %}

enmc/enmc/apps/equipments/templates/equipments_detail.html
{% extends 'equipments_base.html' %}
{% load staticfiles %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
{% endblock %}

{% block content %}
    <section>
{#        <form action="{% url '[equipments]:equipment_detail' %}" method="post" autocomplete="off">#}
        <form id="jsEquipmentForm" method="post" autocomplete="off">
        {% csrf_token %}

        <input type="hidden" name="todo" value="{{ todo }}">

        <div class="form-box" style="margin-top: 110px; margin-bottom: 12%; width: 1100px;">
            <div style="margin:15px;border:0;padding:0;">
                <label style="float:left">所在地区：
                    <select name="country" id="country" style="width: 180px; height: 35px">
                        <option value="{{ equipment.country.countryid }}" selected>{{ equipment.country.name }}</option>
                    </select>
                </label>
                <label style="margin: 12px;">所在机房：
                    <select name="room" id="room" style="width: 180px; height: 35px">
                        <option value="{{ equipment.room.roomid }}" selected>{{ equipment.room.name }}</option>
                    </select>
                </label>
                <label style="margin: 12px;">所在机柜：
                    <select name="cabinet" id="cabinet" style="width: 180px; height: 35px">
                        <option value="{{ equipment.cabinet.cabinetid }}" selected>{{ equipment.cabinet.name }}</option>
                    </select>
                </label>
                </label>
                <label style="float:right">设备ID：<input name="equipmentid" id="equipmentid" type="text"  readonly="readonly" style="width: 180px; height: 35px" value="{% if equipment.equipmentid %}{{ equipment.equipmentid }}{% endif %}"></label>
            </div>
            <div style="margin:15px;border:0;padding:0;">
                <label style="float:left">设备SN：<input name="sn" id="sn" type="text" style="width: 180px; height: 35px;" value="{% if equipment.sn %}{{ equipment.sn }}{% endif %}"></label>
                <label style="margin: 12px;">主机名：<input name="hostname" id="hostname" type="text" required="required" style="width: 180px; height: 35px" value="{% if equipment.hostname %}{{ equipment.hostname }}{% endif %}"></label>
                <label style="margin: 12px;">操作系统：<input name="system" id="system" type="text" style="width: 180px; height: 35px" value="{% if equipment.system %}{{ equipment.system }}{% endif %}"></label>
                <label style="float:right">设备类型：
                    <select name="equipment_type" style="width: 150px; height: 38px">
                        {% for equipment_type in equipment_types %}
                            {% if equipment_type.equipment_typeid == equipment.equipment_type_id %}
                                <option value="{{ equipment_type.equipment_typeid }}" selected>{{ equipment_type.name }}</option>
                            {% else %}
                                <option value="{{ equipment_type.equipment_typeid }}">{{ equipment_type.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select></label>
            </div>
            <div style="margin:15px;border:0;padding:0;">
                <label style="float:left">上联设备：<input name="relatedid" id="relatedid" type="text" style="width: 180px; height: 35px" value="{% if equipment.relatedid %}{{ equipment.relatedid }}{% endif %}"></label>
                <label style="margin: 12px;">上联端口：<input name="relatedport" id="relatedport" type="text" style="width: 180px; height: 35px" value="{% if equipment.relatedport %}{{ equipment.relatedport }}{% endif %}"></label>
                <label style="margin: 12px;">宿主机：<input name="mother" id="mother" type="text" style="width: 180px; height: 35px" value="{% if equipment.mother %}{{ equipment.mother }}{% endif %}"></label>
                <label style="float:right">使用状态：
                    <select name="status" style="width: 150px; height: 38px">
                        {% for status in statuses %}
                            {% if status.id == equipment.status_id %}
                                <option value="{{ status.id }}" selected>{{ status.get_status_display }}</option>
                            {% else %}
                                <option value="{{ status.id }}">{{ status.get_status_display }}</option>
                            {% endif %}
                        {% endfor %}
                    </select></label>
            </div>
            <div style="margin:15px;border:0;padding:0;">
                <label style="float:left">cpu：<input name="cpu" id="cpu" type="text" style="width: 180px; height: 35px" value="{% if equipment.cpu %}{{ equipment.cpu }}{% endif %}"></label>
                <label style="margin: 12px;">内存：<input name="memory" id="memory" type="text" style="width: 200px; height: 35px" value="{% if equipment.memory %}{{ equipment.memory }}{% endif %}"></label>
                <label style="margin: 12px;">磁盘：<input name="disk" id="disk" type="text" style="width: 180px; height: 35px" value="{% if equipment.disk %}{{ equipment.disk }}{% endif %}"></label>
                <label style="float:right">添加时间：<input name="addtime" id="addtime" type="text" readonly="readonly" style="width: 180px; height: 35px" value="{% if equipment.addtime %}{{ equipment.addtime }}{% endif %}"></label>
            </div>
            <div style="margin:15px;border:0;padding:0;">
                <label style="float:left">ip：<input name="ip" id="ip" type="text"
                                                     style="width: 180px; height: 35px" value="{% if equipment.ip %}{{ equipment.ip }}{% endif %}"></label>
                <label style="margin: 12px;">ip2：<input name="ip1" id="ip1" type="text"
                                                        style="width: 180px; height: 35px" value="{% if equipment.ip1 %}{{ equipment.ip1 }}{% endif %}"></label>
                <label style="margin: 12px;">ip3：<input name="ip2" id="ip2" type="text"
                                                        style="width: 180px; height: 35px" value="{% if equipment.ip2 %}{{ equipment.ip2 }}{% endif %}"></label>
                <label style="float:right">ip4：<input name="ip3" id="ip3" type="text"
                                                      style="width: 180px; height: 35px" value="{% if equipment.ip3 %}{{ equipment.ip3 }}{% endif %}"></label>
            </div>
            <div style="margin:15px;border:0;padding:0;">
                <label style="float:left">ip5：<input name="ip4" id="ip4" type="text" style="width: 180px; height: 35px" value="{% if equipment.ip4 %}{{ equipment.ip4 }}{% endif %}"></label>
                <label style="margin: 12px;">ILO地址：<input name="ip9" id="ip9" type="text"
                                                          style="width: 180px; height: 35px" value="{% if equipment.ip9 %}{{ equipment.ip9 }}{% endif %}"></label>
                <label style="margin: 12px;">ssh端口：<input name="ssh_port" id="ssh_port" type="text"
                                                          style="width: 180px; height: 35px" value="{% if equipment.ssh_port %}{{ equipment.ssh_port }}{% endif %}"></label>
                <label style="float:right">更新时间：<input name="updatetime" id="updatetime" type="text" readonly="readonly"
                                                       style="width: 180px; height: 35px" value="{% if equipment.updatetime %}{{ equipment.updatetime }}{% endif %}"></label>
            </div>
            <div style="margin:15px;border:0;padding:0;">
                <label style="margin: 12px;">备注：</label>
                <textarea name="remark" rows="10" cols="30" style="width: 500px; height: 100px">{% if equipment.remark %}{{ equipment.remark }}{% endif %}</textarea>
            </div>

            <div style="height:2px;border-bottom:1px #ccc solid;"></div>

            <div style="margin:15px;border:0;padding:0;">
                <label style="font-size: 20px">服务分类</label>
                <label style="margin: 12px;"><a href="{% url '[equipments]:service_detail' %}?equipmentid={{ equipment.equipmentid }}" style="float:right; font-size: 20px; color: #fb8341">添加服务</a></label>
            </div>

            <div style="width: 500px; margin:auto; margin-top: 30px; border:0;padding:0; ">
                <label style="float:left; width: 125px">服务名</label>
                <label style="float:left; width: 125px">协议类型</label>
                <label style="float:left; width: 125px">服务端口</label>
                <label style="float:right; width: 125px">&nbsp;</label>
            </div>

            {% for service in services %}
                <div style="width: 500px; margin:auto; margin-top: 20px; border:0;padding:0; ">
                    <table border="1">
                        <tr>
                            <a href="{% url '[equipments]:service_detail' %}?equipmentid={{ equipment.equipmentid }}&serviceid={{ service.serviceid }}" style="float:left; width: 125px; margin-top: 10px; border:0;padding:0;">{{ service.name }}</a>
                            <a href="{% url '[equipments]:service_detail' %}?equipmentid={{ equipment.equipmentid }}&serviceid={{ service.serviceid }}" style="float:left; width: 125px; margin-top: 10px; border:0;padding:0;">{{ service.protocol }}</a>
                            <a href="{% url '[equipments]:service_detail' %}?equipmentid={{ equipment.equipmentid }}&serviceid={{ service.serviceid }}" style="float:left; width: 125px; margin-top: 10px; border:0;padding:0;">{{ service.port }}</a>
                            <a href="{% url '[equipments]:service_delete' %}?equipmentid={{ equipment.equipmentid }}&serviceid={{ service.serviceid }}" style="float:right; width: 125px; margin-top: 10px; border:0;padding:0;" onclick="return confirm('你确认要删除吗?')">删除</a>
                        </tr>
                    </table>
                </div>
            {% endfor %}

            <div style="margin:15px; margin-top: 50px; border:0;padding:0;">
                <input class="btn btn-green" id="jsEquipmentBtn" type="button" style="width: 100px"
                       value="提&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;交"/>

                <input class="btn btn-green" type="button"
                       style="width: 100px; margin:10px;border:0;padding:0;"
                       value="返&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;回"
                       onclick="location.href={% url '[equipments]:index' %}"
                />
                {% if todo == 'detail' %}
                    <input class="btn btn-green" id="jsEquipmentDeleteBtn" type="button"
                       style="width: 100px; margin:10px;border:0;padding:0; background: #cc3333"
                       value="删除设备"
                       onclick="location.href={% url '[equipments]:equipment_delete' %}"
                />

                <input class="btn btn-green" type="button"
                       style="width: 100px; margin:10px;border:0;padding:0;"
                       value="克隆设备"
                       onclick="location.href='{% url '[equipments]:equipment_detail' %}?equipmentid={{ equipment.equipmentid }}&todo=clone'"
                />
                {% endif %}
            </div>
        </div>
        </form>
    </section>
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/unslider.js" type="text/javascript"></script>
    <script src="/static/js/login.js" type="text/javascript"></script>
{% endblock %}

{% block custom_js %}
    <script>
    $(function () {
        $('#jsEquipmentBtn').on('click',function () {
            $.ajax({
                cache:false,
                type:'POST',
                url:"{% url '[equipments]:equipment_detail' %}",
                data:$('#jsEquipmentForm').serialize(),
                async:true,
                success: function (data) {
                    console.log(data)
                    if(data.status == 'success'){
                        alert('提交成功'),
                        window.location.href="{% url '[equipments]:index' %}"
                    }else{
                        alert(data.msg)
                    }
                }
            })
        })
    })
    </script>

    <script>
    $(function () {
        $('#jsEquipmentDeleteBtn').on('click',function () {
            $.ajax({
                cache:false,
                type:'POST',
                url:"{% url '[equipments]:equipment_delete' %}",
                data:$('#jsEquipmentForm').serialize(),
                async:true,
                success: function (data) {
                    console.log(data)
                    if(data.status == 'success'){
                        alert(data.msg),
                        window.location.href="{% url '[equipments]:index' %}"
                    }else{
                        {#alert({{ user_detail_form.errors.password2 }})#}
                        alert(data.msg)
                        {#window.location.href="{% url '[equipments]:index' %}"#}
                    }
                }
            })
        })
    })
    </script>
{% endblock %}

enmc/enmc/apps/equipments/templates/service_detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>网管系统</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<header>
</header>
<section>
    <div class="fl form-box" style="width: 550px; margin-top: -80px">
        <h2>编辑服务</h2>
        <form action="{% url '[equipments]:service_detail' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <input name="equipmentid" id="equipmentid" type="hidden" value="{{ equipmentid }}">
            <input name="serviceid" id="serviceid" type="hidden" value="{{ serviceid }}">
            <div class="form-group marb20" style="width: 550px;">
                <label>服务名称</label>
                <input name="name" id="name" type="text" value="{% if service.name %}{{ service.name }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>安装路径</label>
                <input name="install" id="install" type="text" value="{% if service.install %}{{ service.install }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>配置文件</label>
                <input name="config" id="config" type="text" value="{% if service.config %}{{ service.config }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>启动文件</label>
                <input name="start" id="start" type="text" value="{% if service.start %}{{ service.start }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>软件版本</label>
                <input name="version" id="version" type="text" value="{% if service.version %}{{ service.version }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>端口号</label>
                <input name="port" id="port" type="text" value="{% if service.port %}{{ service.port }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>网络协议</label>
                <select name="protocol" style="width: 470px; height: 38px">
                    {% for protocol in protocols %}
                        {% if protocol == service.protocol %}
                            <option value="{{ protocol }}" selected>{{ service.get_protocol_display }}</option>
                        {% else %}
                            <option value="{{ protocol }}">{{ protocol.upper }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>管理用户</label>
                <input name="user" id="user" type="text" value="{% if service.user %}{{ service.user }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>用户密码</label>
                <input name="password" id="password" type="text" value="{% if service.password %}{{ service.password }}{% endif %}">
            </div>
            <div class="form-group marb8" style="width: 550px">
                <label>备注</label>
                <input name="remark" id="remark" type="text" value="{% if service.remark %}{{ service.remark }}{% endif %}">
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">
                {{ msg }}
            </div>
            <input class="btn btn-green" id="xiugaimima" type="submit" value="提交">
        </form>
    </div>
</section>
{#<script src="/static/js/jquery.min.js" type="text/javascript"></script>#}
{#<script src="/static/js/unslider.js" type="text/javascript"></script>#}
{#<script src="/static/js/login.js" type="text/javascript"></script>#}
</body>
</html>